name: Publish antonytm/mcp-sitecore-windows to Docker Hub
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: antonytm/mcp-sitecore-windows
          tags: 1.0.0, latest
          registry: docker.io
          dockerfile: ./docker/windows/Dockerfile
          platform: windows/amd64
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
